date	prefix	url	message	context
2022-09-15	3dmet	http://www.3dmet.dna.affrc.go.jp/cgi/show_data.php?acc=B00162	ConnectTimeout	HTTPConnectionPool(host='www.3dmet.dna.affrc.go.jp', port=80): Max retries exceeded with url: /cgi/show_data.php?acc=B00162 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x11f8e0f70>, 'Connection to www.3dmet.dna.affrc.go.jp timed out. (connect timeout=15)'))
2022-09-15	abm	https://www.abmgood.com/catalogsearch/result/?cat=&q=T0599	HTTP 403	403
2022-09-15	addexbio	https://www.addexbio.com/productdetail?pid=C0020004/4992	HTTP 404	404
2022-09-15	ado	https://www.ebi.ac.uk/ols/ontologies/ado/terms?iri=http://purl.obolibrary.org/obo/ADO_0000001	HTTP 404	404
2022-09-15	aftol.taxonomy	http://wasabi.lutzonilab.net/pub/displayTaxonInfo?aftol_id=959	ConnectionError	HTTPConnectionPool(host='wasabi.lutzonilab.net', port=80): Max retries exceeded with url: /pub/displayTaxonInfo?aftol_id=959 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f8e0a30>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2022-09-15	apaonto	http://ontology.apa.org/apaonto/termsonlyOUT%20(5).owl#Abdomen	ConnectionError	HTTPConnectionPool(host='ontology.apa.org', port=80): Max retries exceeded with url: /apaonto/termsonlyOUT%20(5).owl (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f9cb790>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2022-09-15	apd	http://aps.unmc.edu/AP/database/query_output.php?ID=01001	ConnectionError	HTTPConnectionPool(host='aps.unmc.edu', port=80): Max retries exceeded with url: /AP/database/query_output.php?ID=01001 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11ec643a0>: Failed to establish a new connection: [Errno 61] Connection refused'))
2022-09-15	arachnoserver	http://www.arachnoserver.org/toxincard.html?id=AS000060	ConnectionError	HTTPConnectionPool(host='www.arachnoserver.org', port=80): Max retries exceeded with url: /toxincard.html?id=AS000060 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11ecbad90>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2022-09-15	ardb	http://ardb.cbcb.umd.edu/cgi/search.cgi?db=L&amp;field=ni&amp;term=CAE46076	HTTP 404	404
2022-09-15	arraymap	https://www.arraymap.org/pgx:icdom:8500_3	HTTP 525	525
2022-09-15	asin	https://amzn.com/0471491039	HTTP 404	404
2022-09-15	aspgd.locus	http://www.aspergillusgenome.org/cgi-bin/locus.pl?dbid=ASPL0000349247	ConnectTimeout	HTTPConnectionPool(host='www.aspergillusgenome.org', port=80): Max retries exceeded with url: /cgi-bin/locus.pl?dbid=ASPL0000349247 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x11fa020d0>, 'Connection to www.aspergillusgenome.org timed out. (connect timeout=15)'))
2022-09-15	aspgd.protein	http://www.aspergillusgenome.org/cgi-bin/protein/proteinPage.pl?dbid=ASPL0000349247	ConnectTimeout	HTTPConnectionPool(host='www.aspergillusgenome.org', port=80): Max retries exceeded with url: /cgi-bin/protein/proteinPage.pl?dbid=ASPL0000349247 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x11f9e7af0>, 'Connection to www.aspergillusgenome.org timed out. (connect timeout=15)'))
2022-09-15	atfdb.family	http://www.bioguo.org/AnimalTFDB/family.php?fam=CUT	HTTP 404	404
2022-09-15	atol	http://opendata.inra.fr/ATOL/ATOL_0002233	SSLError	HTTPSConnectionPool(host='opendata.inra.fr', port=443): Max retries exceeded with url: /ATOL/ATOL_0002233 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)')))
2022-09-15	bcio	https://w3id.org/BCI-ontology#040000	ConnectionError	HTTPConnectionPool(host='bci.pet.cs.nctu.edu.tw', port=80): Max retries exceeded with url: /ontology (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f9e7310>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2022-09-15	bco	http://purl.obolibrary.org/obo/BCO_0000081	HTTP 404	404
2022-09-15	bcrc	https://catalog.bcrc.firdi.org.tw/BcrcContent?bid=60316	SSLError	HTTPSConnectionPool(host='catalog.bcrc.firdi.org.tw', port=443): Max retries exceeded with url: /BcrcContent?bid=60316 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))
2022-09-15	beetlebase	http://beetlebase.org/cgi-bin/gbrowse/BeetleBase3.gff3/?name=TC010103	ConnectTimeout	HTTPConnectionPool(host='beetlebase.org', port=80): Max retries exceeded with url: /cgi-bin/gbrowse/BeetleBase3.gff3/?name=TC010103 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x11fa13c70>, 'Connection to beetlebase.org timed out. (connect timeout=15)'))
2022-09-15	biocarta.pathway	https://cgap.nci.nih.gov/Pathways/BioCarta/h_aktPathway	ConnectTimeout	HTTPSConnectionPool(host='cgap.nci.nih.gov', port=443): Max retries exceeded with url: /Pathways/BioCarta/h_aktPathway (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x11f9f4820>, 'Connection to cgap.nci.nih.gov timed out. (connect timeout=15)'))
2022-09-15	biocatalogue.service	https://www.biocatalogue.org/services/614	HTTP 403	403
2022-09-15	biominder	https://datalab.rwth-aachen.de/MINDER/resource/aef4c195-9cf9-46db-a12a-7cfd1ff3eec3	HTTP 502	502
2022-09-15	biomodels.db	https://www.ebi.ac.uk/biomodels/BIOMD0000000048	HTTP 415	415
2022-09-15	biomodels.kisao	https://www.biomodels.net/kisao/KISAO#KISAO_0000057	SSLError	"HTTPSConnectionPool(host='www.biomodels.net', port=443): Max retries exceeded with url: /kisao/KISAO (Caused by SSLError(CertificateError(""hostname 'www.biomodels.net' doesn't match either of 'www4.ebi.ac.uk', 'www.www4.ebi.ac.uk'"")))"
2022-09-15	biomodels.vocabulary	http://biomodels.net/rdf/vocabulary.rdf#rateRule	HTTP 404	404
2022-09-15	biosystems	https://www.ncbi.nlm.nih.gov/biosystems/001	HTTP 404	404
2022-09-15	bitterdb.cpd	http://bitterdb.agri.huji.ac.il/bitterdb/compound.php?id=46	SSLError	HTTPSConnectionPool(host='bitterdb.agri.huji.ac.il', port=443): Max retries exceeded with url: /bitterdb/compound.php?id=46 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))
2022-09-15	bitterdb.rec	http://bitterdb.agri.huji.ac.il/Receptor.php?id=1	SSLError	HTTPSConnectionPool(host='bitterdb.agri.huji.ac.il', port=443): Max retries exceeded with url: /Receptor.php?id=1 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))
2022-09-15	bmrb	http://rest.bmrb.wisc.edu/bmrb/15000/html	HTTP 404	404
2022-09-15	brenda.ligandgroup	https://www.brenda-enzymes.de/ligand.php?brenda_group_id=18030	ReadTimeout	HTTPSConnectionPool(host='www.brenda-enzymes.de', port=443): Read timed out. (read timeout=15)
2022-09-15	bs	https://biopragmatics.github.io/providers/bs/00042	HTTP 404	404
2022-09-15	bugbase.expt	http://bugs.sgul.ac.uk/bugsbase/tabs/experiment.php?expt_id=288&action=view	ConnectTimeout	HTTPConnectionPool(host='bugs.sgul.ac.uk', port=80): Max retries exceeded with url: /bugsbase/tabs/experiment.php?expt_id=288&action=view (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x11ee3b070>, 'Connection to bugs.sgul.ac.uk timed out. (connect timeout=15)'))
2022-09-15	bugbase.protocol	http://bugs.sgul.ac.uk/bugsbase/tabs/protocol.php?protocol_id=67&amp;action=view	ConnectTimeout	HTTPConnectionPool(host='bugs.sgul.ac.uk', port=80): Max retries exceeded with url: /bugsbase/tabs/protocol.php?protocol_id=67&amp;action=view (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x11ee3bd60>, 'Connection to bugs.sgul.ac.uk timed out. (connect timeout=15)'))
2022-09-15	bykdb	https://bykdb.ibcp.fr/data/html/annotated/A0A009E7X8.html	SSLError	"HTTPSConnectionPool(host='bykdb.ibcp.fr', port=443): Max retries exceeded with url: /data/html/annotated/A0A009E7X8.html (Caused by SSLError(CertificateError(""hostname 'bykdb.ibcp.fr' doesn't match either of 'npsa-prabi.ibcp.fr', 'npsa-pbil.ibcp.fr'"")))"
2022-09-15	ccds	http://www.ncbi.nlm.nih.gov/CCDS/CcdsBrowse.cgi?REQUEST=CCDS&DATA=CCDS13573.1	ReadTimeout	HTTPSConnectionPool(host='www.ncbi.nlm.nih.gov', port=443): Read timed out. (read timeout=15)
2022-09-15	cdpd	http://webprod3.hc-sc.gc.ca/dpd-bdpp/info.do?lang=eng&code=63250	ConnectionError	HTTPConnectionPool(host='webprod3.hc-sc.gc.ca', port=80): Max retries exceeded with url: /dpd-bdpp/info.do?lang=eng&code=63250 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f7c0b20>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2022-09-15	cellbank.australia	https://www.cellbankaustralia.com/ab-1-ha.html	HTTP 404	404
2022-09-15	cghdb	http://www.cghtmd.jp/CGHDatabase/mapViewer?hid=300165/p13898_2106T&aid=%t&lang=en	SSLError	HTTPSConnectionPool(host='www.cghtmd.jp', port=443): Max retries exceeded with url: /CNVDatabase?hid=300165/p13898_2106T&aid=%2525t&lang=en (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)')))
2022-09-15	charprot	http://www.jcvi.org/charprotdb/index.cgi/view/CH_001923	HTTP 404	404
2022-09-15	clinvar	https://www.ncbi.nlm.nih.gov/clinvar/variation/12345	HTTP 502	502
2022-09-15	clinvar.submission	http://www.ncbi.nlm.nih.gov/clinvar?term=SCV000151292	HTTP 502	502
2022-09-15	cls	https://cls.shop/300108/p3934_A-172	HTTP 404	404
2022-09-15	cmecs	https://cmecscatalog.org/cmecs/classification/unit/595.html	SSLError	"HTTPSConnectionPool(host='cmecscatalog.org', port=443): Max retries exceeded with url: /cmecs/classification/unit/595.html (Caused by SSLError(CertificateError(""hostname 'cmecscatalog.org' doesn't match either of '*.parkingcrew.net', 'parkingcrew.net'"")))"
2022-09-15	co_320	https://www.cropontology.org/rdf/CO_320:0000618	ConnectionError	HTTPSConnectionPool(host='cropontology.orgrdf', port=443): Max retries exceeded with url: /CO_320:0000618 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11f7c5d00>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2022-09-15	co_321	https://www.cropontology.org/rdf/CO_321:0000449	ConnectionError	HTTPSConnectionPool(host='cropontology.orgrdf', port=443): Max retries exceeded with url: /CO_321:0000449 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11fa4de20>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2022-09-15	co_322	https://www.cropontology.org/rdf/CO_322:0000773	ConnectionError	HTTPSConnectionPool(host='cropontology.orgrdf', port=443): Max retries exceeded with url: /CO_322:0000773 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11ee3b250>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2022-09-15	co_323	https://www.cropontology.org/rdf/CO_323:0000252	ConnectionError	HTTPSConnectionPool(host='cropontology.orgrdf', port=443): Max retries exceeded with url: /CO_323:0000252 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11fa32880>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2022-09-15	co_324	https://www.cropontology.org/rdf/CO_324:0000111	ConnectionError	HTTPSConnectionPool(host='cropontology.orgrdf', port=443): Max retries exceeded with url: /CO_324:0000111 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11f34c9d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2022-09-15	co_325	https://www.cropontology.org/rdf/CO_325:0000519	ConnectionError	HTTPSConnectionPool(host='cropontology.orgrdf', port=443): Max retries exceeded with url: /CO_325:0000519 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11f34c940>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2022-09-15	co_326	https://www.cropontology.org/rdf/CO_326:0000254	ConnectionError	HTTPSConnectionPool(host='cropontology.orgrdf', port=443): Max retries exceeded with url: /CO_326:0000254 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11fa27670>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2022-09-15	co_327	https://www.cropontology.org/rdf/CO_327:0000095	ConnectionError	HTTPSConnectionPool(host='cropontology.orgrdf', port=443): Max retries exceeded with url: /CO_327:0000095 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11fa4d8e0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2022-09-15	co_330	https://www.cropontology.org/rdf/CO_330:0000106	ConnectionError	HTTPSConnectionPool(host='cropontology.orgrdf', port=443): Max retries exceeded with url: /CO_330:0000106 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11f9e7f10>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2022-09-15	co_331	https://www.cropontology.org/rdf/CO_331:0000088	ConnectionError	HTTPSConnectionPool(host='cropontology.orgrdf', port=443): Max retries exceeded with url: /CO_331:0000088 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11f34c880>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2022-09-15	co_333	https://www.cropontology.org/rdf/CO_333:3000045	ConnectionError	HTTPSConnectionPool(host='cropontology.orgrdf', port=443): Max retries exceeded with url: /CO_333:3000045 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11f9e7af0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2022-09-15	co_334	https://www.cropontology.org/rdf/CO_334:0000070	ConnectionError	HTTPSConnectionPool(host='cropontology.orgrdf', port=443): Max retries exceeded with url: /CO_334:0000070 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11f34c940>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2022-09-15	co_335	https://www.cropontology.org/rdf/CO_335:0000189	ConnectionError	HTTPSConnectionPool(host='cropontology.orgrdf', port=443): Max retries exceeded with url: /CO_335:0000189 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11fa5b190>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2022-09-15	co_336	https://www.cropontology.org/rdf/CO_336:0000339	ConnectionError	HTTPSConnectionPool(host='cropontology.orgrdf', port=443): Max retries exceeded with url: /CO_336:0000339 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11fa5b340>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2022-09-15	co_337	https://www.cropontology.org/rdf/CO_337:0000054	ConnectionError	HTTPSConnectionPool(host='cropontology.orgrdf', port=443): Max retries exceeded with url: /CO_337:0000054 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11fa32760>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2022-09-15	co_338	https://www.cropontology.org/rdf/CO_338:0000138	ConnectionError	HTTPSConnectionPool(host='cropontology.orgrdf', port=443): Max retries exceeded with url: /CO_338:0000138 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11f34c640>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2022-09-15	co_339	https://www.cropontology.org/rdf/CO_339:0000032	ConnectionError	HTTPSConnectionPool(host='cropontology.orgrdf', port=443): Max retries exceeded with url: /CO_339:0000032 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11f7d53d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2022-09-15	co_340	https://www.cropontology.org/rdf/CO_340:0000639	ConnectionError	HTTPSConnectionPool(host='cropontology.orgrdf', port=443): Max retries exceeded with url: /CO_340:0000639 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11fa32f40>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2022-09-15	co_341	https://www.cropontology.org/rdf/CO_341:0000140	ConnectionError	HTTPSConnectionPool(host='cropontology.orgrdf', port=443): Max retries exceeded with url: /CO_341:0000140 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11f9f4f10>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2022-09-15	co_343	https://www.cropontology.org/rdf/CO_343:0100010	ConnectionError	HTTPSConnectionPool(host='cropontology.orgrdf', port=443): Max retries exceeded with url: /CO_343:0100010 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11ef10f10>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2022-09-15	co_345	https://www.cropontology.org/rdf/CO_345:0000127	ConnectionError	HTTPSConnectionPool(host='cropontology.orgrdf', port=443): Max retries exceeded with url: /CO_345:0000127 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11fa4d880>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2022-09-15	co_346	https://www.cropontology.org/rdf/CO_346:0000199	ConnectionError	HTTPSConnectionPool(host='cropontology.orgrdf', port=443): Max retries exceeded with url: /CO_346:0000199 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11f9f4940>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2022-09-15	co_347	https://www.cropontology.org/rdf/CO_347:0000108	ConnectionError	HTTPSConnectionPool(host='cropontology.orgrdf', port=443): Max retries exceeded with url: /CO_347:0000108 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11f8f3f40>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2022-09-15	co_348	https://www.cropontology.org/rdf/CO_348:1100107	ConnectionError	HTTPSConnectionPool(host='cropontology.orgrdf', port=443): Max retries exceeded with url: /CO_348:1100107 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11f9f4ca0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2022-09-15	co_350	https://www.cropontology.org/rdf/CO_350:0000215	ConnectionError	HTTPSConnectionPool(host='cropontology.orgrdf', port=443): Max retries exceeded with url: /CO_350:0000215 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11fa5f0d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2022-09-15	co_356	https://www.cropontology.org/rdf/CO_356:4000027	ConnectionError	HTTPSConnectionPool(host='cropontology.orgrdf', port=443): Max retries exceeded with url: /CO_356:4000027 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11fa5f250>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2022-09-15	co_357	https://www.cropontology.org/rdf/CO_357:1000290	ConnectionError	HTTPSConnectionPool(host='cropontology.orgrdf', port=443): Max retries exceeded with url: /CO_357:1000290 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11ee31400>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2022-09-15	co_358	https://www.cropontology.org/rdf/CO_358:0000139	ConnectionError	HTTPSConnectionPool(host='cropontology.orgrdf', port=443): Max retries exceeded with url: /CO_358:0000139 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11ee31e20>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2022-09-15	co_359	https://www.cropontology.org/rdf/CO_359:0000947	ConnectionError	HTTPSConnectionPool(host='cropontology.orgrdf', port=443): Max retries exceeded with url: /CO_359:0000947 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11f9bbb20>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2022-09-15	co_360	https://www.cropontology.org/rdf/CO_360:0000071	ConnectionError	HTTPSConnectionPool(host='cropontology.orgrdf', port=443): Max retries exceeded with url: /CO_360:0000071 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11fa32ac0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2022-09-15	co_365	https://www.cropontology.org/rdf/CO_365:0000205	ConnectionError	HTTPSConnectionPool(host='cropontology.orgrdf', port=443): Max retries exceeded with url: /CO_365:0000205 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11f7ce190>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2022-09-15	co_366	https://www.cropontology.org/rdf/CO_366:0000072	ConnectionError	HTTPSConnectionPool(host='cropontology.orgrdf', port=443): Max retries exceeded with url: /CO_366:0000072 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11f9cb370>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2022-09-15	come	https://www.flymine.org/come/entry?gn=MOL000160	ReadTimeout	HTTPSConnectionPool(host='www.flymine.org', port=443): Read timed out. (read timeout=15)
2022-09-15	compulyeast	http://compluyeast2dpage.dacya.ucm.es/cgi-bin/2d/2d.cgi?ac=O08709	ConnectionError	HTTPConnectionPool(host='compluyeast2dpage.dacya.ucm.es', port=80): Max retries exceeded with url: /cgi-bin/2d/2d.cgi?ac=O08709 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11ee3b2b0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2022-09-15	crisprdb	http://crispr.i2bc.paris-saclay.fr/cgi-bin/crispr/SpecieProperties_db.cgi?Taxon_id[]=551115	SSLError	HTTPSConnectionPool(host='crispr.i2bc.paris-saclay.fr', port=443): Max retries exceeded with url: /cgi-bin/crispr/SpecieProperties_db.cgi?Taxon_id%255B%255D=551115 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)')))
2022-09-15	darc	http://darcsite.genzentrum.lmu.de/darc/view.php?id=1250	ConnectionError	HTTPConnectionPool(host='darcsite.genzentrum.lmu.de', port=80): Max retries exceeded with url: /darc/view.php?id=1250 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11fa7a070>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2022-09-15	dbd	http://www.transcriptionfactor.org/index.cgi?Search/Domain+domain:0045310+cat:DBD	HTTP 404	404
2022-09-15	dbprobe	https://www.ncbi.nlm.nih.gov/probe/?term=1000000	HTTP 410	410
2022-09-15	dev.ga4ghdos	https://dos-gdc.ucsc-cgp-dev.org/ga4gh/dos/v1/dataobjects/23fa7b4b-9d68-429b-aece-658b11124bb3#2017-03-24T18:43:16.886826-05:00	ConnectionError	HTTPSConnectionPool(host='dos-gdc.ucsc-cgp-dev.org', port=443): Max retries exceeded with url: /ga4gh/dos/v1/dataobjects/23fa7b4b-9d68-429b-aece-658b11124bb3 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11f7c5460>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2022-09-15	dicom	http://dicom.nema.org/resources/ontology/DCM/109082	HTTP 404	404
2022-09-15	dictybase	http://dictybase.org/gene/DDB0191090	HTTP 500	500
2022-09-15	dip	https://dip.doe-mbi.ucla.edu/dip/DIPview.cgi?ID=DIP-743N	SSLError	HTTPSConnectionPool(host='dip.doe-mbi.ucla.edu', port=443): Max retries exceeded with url: /dip/DIPview.cgi?ID=DIP-743N (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))
2022-09-15	diseasesdb	https://www.diseasesdatabase.com/ddb1784.htm	ConnectTimeout	HTTPSConnectionPool(host='www.diseasesdatabase.com', port=443): Max retries exceeded with url: /ddb1784.htm (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x11fa32340>, 'Connection to www.diseasesdatabase.com timed out. (connect timeout=15)'))
2022-09-15	dommino	http://orion.rnet.missouri.edu/~nz953/DOMMINO/index.php/result/show_network/2GC4	ConnectTimeout	HTTPConnectionPool(host='orion.rnet.missouri.edu', port=80): Max retries exceeded with url: /~nz953/DOMMINO/index.php/result/show_network/2GC4 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x11f7d7280>, 'Connection to orion.rnet.missouri.edu timed out. (connect timeout=15)'))
2022-09-15	dpv	http://www.dpvweb.net/dpv/showdpv.php?dpvno=100	HTTP 404	404
2022-09-15	dto	http://www.drugtargetontology.org/dto/DTO_90000018	HTTP 404	404
2022-09-15	ecogene	http://www.ecogene.org/gene/EG10173	ConnectTimeout	HTTPConnectionPool(host='www.ecogene.org', port=80): Max retries exceeded with url: /gene/EG10173 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x11f81bf40>, 'Connection to www.ecogene.org timed out. (connect timeout=15)'))
2022-09-15	edda	http://ontologies.dbmi.pitt.edu/edda/StudyDesigns.owl#health_care_quality_assessment	ConnectionError	HTTPConnectionPool(host='ontologies.dbmi.pitt.edu', port=80): Max retries exceeded with url: /edda/StudyDesigns.owl (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11fa36fd0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2022-09-15	enm	http://purl.enanomapper.org/onto/ENM_8000221	ConnectionError	HTTPConnectionPool(host='purl.enanomapper.org', port=80): Max retries exceeded with url: /onto/ENM_8000221 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f840a00>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2022-09-15	ensembl.fungi	https://fungi.ensembl.org/id/CADAFLAT00006211	ReadTimeout	HTTPSConnectionPool(host='fungi.ensembl.org', port=443): Read timed out. (read timeout=15)
2022-09-15	epio	http://purl.obolibrary.org/obo/EPIO_0000011	HTTP 404	404
2022-09-15	epso	http://www.case.edu/EpilepsyOntology.owl#0000400	HTTP 404	404
2022-09-15	euclinicaltrials	https://www.clinicaltrialsregister.eu/ctr-search/search?query=2008-005144-16	SSLError	HTTPSConnectionPool(host='www.clinicaltrialsregister.eu', port=443): Max retries exceeded with url: /ctr-search/search?query=2008-005144-16 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))
2022-09-15	exac.gene	http://exac.broadinstitute.org/gene/ENSG00000169174	HTTP 404	404
2022-09-15	exac.transcript	http://exac.broadinstitute.org/transcript/ENST00000407236	HTTP 404	404
2022-09-15	exac.variant	http://exac.broadinstitute.org/variant/22-46615880-T-C	HTTP 404	404
2022-09-15	fbbt	https://flybase.org/cgi-bin/cvreport.pl?id=FBbt:00007294	HTTP 403	403
2022-09-15	fbrf	https://flybase.org/reports/FBrf0187632	HTTP 403	403
2022-09-15	fbtc	https://flybase.org/reports/FBtc0000190	HTTP 403	403
2022-09-15	fcb	https://w3id.org/faircookbook/FCB005	SSLError	HTTPSConnectionPool(host='faircookbook.elixir-europe.org', port=443): Max retries exceeded with url: /content/recipes/infrastructure/vocabularies/UC3_R13_local_ontology_services.html (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))
2022-09-15	fishbase.species	https://www.fishbase.ca/summary/6472	HTTP 403	403
2022-09-15	flybase	https://flybase.org/reports/FBgn0011293	HTTP 403	403
2022-09-15	foaf	http://xmlns.com/foaf/0.1/familyName	HTTP 404	404
2022-09-15	foodb.food	https://foodb.ca/foods/FOOD00020	HTTP 500	500
2022-09-15	fossilworks.journal	http://fossilworks.org/?a=referenceInfo&reference_no=61467	ConnectionError	HTTPConnectionPool(host='fossilworks.org', port=80): Max retries exceeded with url: /?a=referenceInfo&reference_no=61467 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11efcc460>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2022-09-15	fsnp	http://compbio.cs.queensu.ca/cgi-bin/compbio/search/main.cgi?search_mode=id&amp;id_type=snp_id&amp;id_val=rs17852708	ConnectTimeout	HTTPConnectionPool(host='compbio.cs.queensu.ca', port=80): Max retries exceeded with url: /cgi-bin/compbio/search/main.cgi?search_mode=id&amp;id_type=snp_id&amp;id_val=rs17852708 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x11f9e7bb0>, 'Connection to compbio.cs.queensu.ca timed out. (connect timeout=15)'))
2022-09-15	funcbase.fly	http://func.mshri.on.ca/fly/genes/list_functional_scores/10194	ConnectionError	HTTPConnectionPool(host='func.mshri.on.ca', port=80): Max retries exceeded with url: /fly/genes/list_functional_scores/10194 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11fa6d580>: Failed to establish a new connection: [Errno 51] Network is unreachable'))
2022-09-15	funcbase.human	http://func.mshri.on.ca/human/genes/list_functional_scores/119514	ConnectionError	HTTPConnectionPool(host='func.mshri.on.ca', port=80): Max retries exceeded with url: /human/genes/list_functional_scores/119514 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11fa32d60>: Failed to establish a new connection: [Errno 51] Network is unreachable'))
2022-09-15	funcbase.mouse	http://func.mshri.on.ca/mouse/genes/list_functional_scores/1351341	ConnectionError	HTTPConnectionPool(host='func.mshri.on.ca', port=80): Max retries exceeded with url: /mouse/genes/list_functional_scores/1351341 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f84dd90>: Failed to establish a new connection: [Errno 51] Network is unreachable'))
2022-09-15	funcbase.yeast	http://func.mshri.on.ca/yeast/genes/list_functional_scores/2701	ConnectionError	HTTPConnectionPool(host='func.mshri.on.ca', port=80): Max retries exceeded with url: /yeast/genes/list_functional_scores/2701 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f7cc040>: Failed to establish a new connection: [Errno 51] Network is unreachable'))
2022-09-15	gabi	http://www.gabipd.org/database/cgi-bin/GreenCards.pl.cgi?BioObjectId=2679240&Mode=ShowBioObject	HTTP 404	404
2022-09-15	gard	https://rarediseases.info.nih.gov/diseases/6038/index	HTTP 404	404
2022-09-15	gc	https://www.ncbi.nlm.nih.gov/Taxonomy/taxonomyhome.html/index.cgi?chapter=cgencodes#SG11	ReadTimeout	HTTPSConnectionPool(host='www.ncbi.nlm.nih.gov', port=443): Read timed out. (read timeout=15)
2022-09-15	genecards	https://www.genecards.org/cgi-bin/carddisp.pl?gene=ABL1	HTTP 403	403
2022-09-15	genefarm	https://urgi.versailles.inra.fr/Genefarm/Gene/display_gene.htpl?GENE_ID=4892	HTTP 503	503
2022-09-15	glida.gpcr	http://pharminfo.pharm.kyoto-u.ac.jp/services/glida/gpcr_information.php?id=ACM1_HUMAN	HTTP 404	404
2022-09-15	glida.ligand	http://pharminfo.pharm.kyoto-u.ac.jp/services/glida/ligand_information.php?id=L000001	HTTP 404	404
2022-09-15	gmd	http://gmd.mpimp-golm.mpg.de/Metabolites/68513255-fc44-4041-bc4b-4fd2fae7541d.aspx	ReadTimeout	HTTPConnectionPool(host='gmd.mpimp-golm.mpg.de', port=80): Read timed out. (read timeout=15)
2022-09-15	graingenes.reference	https://wheat.pw.usda.gov/cgi-bin/GG3/report.cgi?class=reference&name=WGS-95-1333	SSLError	HTTPSConnectionPool(host='wheat.pw.usda.gov', port=443): Max retries exceeded with url: /cgi-bin/GG3/report.cgi?class=reference&name=WGS-95-1333 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))
2022-09-15	graingenes.symbol	http://wheat.pw.usda.gov/report?class=gene;name=1-FEH+w3	ConnectionError	HTTPConnectionPool(host='wheat.pw.usda.gov', port=80): Max retries exceeded with url: /report?class=gene;name=1-FEH+w3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f867b20>: Failed to establish a new connection: [Errno 61] Connection refused'))
2022-09-15	greengenes	http://greengenes.lbl.gov/cgi-bin/show_one_record_v2.pl?prokMSA_id=100000	HTTP 404	404
2022-09-15	grin.taxonomy	http://www.ars-grin.gov/cgi-bin/npgs/html/taxon.pl?19333	HTTP 404	404
2022-09-15	grsdb	http://bioinformatics.ramapo.edu/GRSDB2/geneview.php?geneID=10142	HTTP 500	500
2022-09-15	gwascentral.marker	https://www.gwascentral.org/marker/HGVM15354	HTTP 403	403
2022-09-15	hcvdb	https://euhcvdb.ibcp.fr/euHCVdb/do/displayHCVEntry?primaryAC=M58335	SSLError	"HTTPSConnectionPool(host='euhcvdb.ibcp.fr', port=443): Max retries exceeded with url: /euHCVdb/do/displayHCVEntry?primaryAC=M58335 (Caused by SSLError(CertificateError(""hostname 'euhcvdb.ibcp.fr' doesn't match either of 'npsa-prabi.ibcp.fr', 'npsa-pbil.ibcp.fr'"")))"
2022-09-15	hdr	http://research.nhgri.nih.gov/apps/homeodomain/web/index.cgi?mode=view&amp;view=proteins&amp;id=63	HTTP 404	404
2022-09-15	hogenom	http://pbil.univ-lyon1.fr/cgi-bin/view-tree.pl?db=HOGENOM5&query=HBG284870	HTTP 404	404
2022-09-15	homd.seq	http://www.homd.org/modules.php?op=modload&name=GenomeList&file=index&link=detailinfo&seqid=SEQF1003	HTTP 404	404
2022-09-15	homd.taxon	http://www.homd.org/modules.php?op=modload&name=HOMD&view=dynamic&oraltaxonid=811	HTTP 404	404
2022-09-15	hovergen	http://pbil.univ-lyon1.fr/cgi-bin/view-tree.pl?query=HBG004341&db=HOVERGEN	HTTP 404	404
2022-09-15	hp	https://hpo.jax.org/app/browse/term/HP:0011140	SSLError	HTTPSConnectionPool(host='hpo.jax.org', port=443): Max retries exceeded with url: /app/browse/term/HP:0011140 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))
2022-09-15	hpm.protein	http://www.humanproteomemap.org/protein.php?hpm_id=1968	ConnectionError	HTTPConnectionPool(host='www.humanproteomemap.org', port=80): Read timed out.
2022-09-15	hssp	ftp://ftp.embl-heidelberg.de/pub/databases/protein_extras/hssp/102l.hssp.bz2	InvalidSchema	No connection adapters were found for 'ftp://ftp.embl-heidelberg.de/pub/databases/protein_extras/hssp/102l.hssp.bz2'
2022-09-15	icd10cm	https://icd.codes/icd10cm/F45.21	HTTP 404	404
2022-09-15	iceberg.element	http://db-mml.sjtu.edu.cn/ICEberg/feature_page.php?ice_id=100	HTTP 404	404
2022-09-15	iceberg.family	http://db-mml.sjtu.edu.cn/ICEberg/browse_result.php?type=fam&fam_id=1	HTTP 404	404
2022-09-15	idoden	http://purl.bioontology.org/ontology/IDODEN_0003463	HTTP 404	404
2022-09-15	idoo	http://registry.api.hq.identifiers.org/semanticApi/getRegistryOntology#DataCollection	ConnectionError	HTTPConnectionPool(host='registry.api.hq.identifiers.org', port=80): Max retries exceeded with url: /semanticApi/getRegistryOntology (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f878ca0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2022-09-15	idot	https://biomodels.net/vocab/idot.rdf#identifierPattern	SSLError	"HTTPSConnectionPool(host='biomodels.net', port=443): Max retries exceeded with url: /vocab/idot.rdf (Caused by SSLError(CertificateError(""hostname 'biomodels.net' doesn't match either of 'www4.ebi.ac.uk', 'www.www4.ebi.ac.uk'"")))"
2022-09-15	igsr	https://www.internationalgenome.org/data-portal/sample/NA06985	SSLError	HTTPSConnectionPool(host='www.internationalgenome.org', port=443): Max retries exceeded with url: /data-portal/sample/NA06985 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)')))
2022-09-15	imanis	https://www.imanislife.com/?s=CL070	SSLError	HTTPSConnectionPool(host='www.imanislife.com', port=443): Max retries exceeded with url: /?s=CL070 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))
2022-09-15	imgt.hla	https://www.ebi.ac.uk/cgi-bin/imgt/hla/get_allele.cgi?A*01:01:01:01	HTTP 404	404
2022-09-15	inn	https://mednet-communities.net/inn/db/ViewINN.aspx?i=fluticasone	HTTP 404	404
2022-09-15	ird.segment	http://www.fludb.org/brc/fluSegmentDetails.do?ncbiGenomicAccession=CY077097	HTTP 404	404
2022-09-15	irefweb	http://wodaklab.org/iRefWeb/interaction/show/617102	SSLError	HTTPSConnectionPool(host='wodaklab.org', port=443): Max retries exceeded with url: /iRefWeb/interaction/show/617102 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)')))
2022-09-15	isfinder	https://www-is.biotoul.fr/scripts/ficheIS.php?name=ISA1083-2	SSLError	HTTPSConnectionPool(host='www-is.biotoul.fr', port=443): Max retries exceeded with url: /scripts/ficheIS.php?name=ISA1083-2 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))
2022-09-15	ito	https://bioportal.bioontology.org/ontologies/ITO/?p=classes&conceptid=https%3A%2F%2Fai-strategies.org%2Fontology%2FITO_01625	HTTP 404	404
2022-09-15	jstor	http://www.jstor.org/stable/3075966	HTTP 420	420
2022-09-15	kclb	https://cellbank.snu.ac.kr/english/sub/catalog.php?s_cellid=464&page=detail_info&CatNo=59&strQ=10020.2	ConnectionError	('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))
2022-09-15	langual	https://www.langual.org/langual_thesaurus.asp?termid=B2067	HTTP 406	406
2022-09-15	limore	https://www.picb.ac.cn/limore/cellLines/single?para=Li7	HTTP 403	403
2022-09-15	linkml	https://w3id.org/linkml/SchemaDefinition	SSLError	HTTPSConnectionPool(host='linkml.io', port=443): Max retries exceeded with url: /linkml-model/SchemaDefinition (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))
2022-09-15	lipidbank	http://lipidbank.jp/cgi-bin/detail.cgi?id=BBA0001	HTTP 404	404
2022-09-15	lrg	ftp://ftp.ebi.ac.uk/pub/databases/lrgex/1.xml	InvalidSchema	No connection adapters were found for 'ftp://ftp.ebi.ac.uk/pub/databases/lrgex/1.xml'
2022-09-15	mesh.2012	http://www.nlm.nih.gov/cgi/mesh/2012/MB_cgi?mode=&index=17186&view=expanded	HTTP 500	500
2022-09-15	mesh.2013	http://www.nlm.nih.gov/cgi/mesh/2013/MB_cgi?mode=&index=17165&view=expanded	HTTP 500	500
2022-09-15	mex	https://www.metabolome-express.org/datasetview.php?datasetid=36	ConnectionError	HTTPSConnectionPool(host='www.metabolome-express.org', port=443): Max retries exceeded with url: /datasetview.php?datasetid=36 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11f8379a0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2022-09-15	mge	http://aclame.ulb.ac.be/perl/Aclame/Genomes/mge_view.cgi?view=info&id=mge:2	ConnectTimeout	HTTPConnectionPool(host='aclame.ulb.ac.be', port=80): Max retries exceeded with url: /perl/Aclame/Genomes/mge_view.cgi?view=info&id=mge:2 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x11f881d90>, 'Connection to aclame.ulb.ac.be timed out. (connect timeout=15)'))
2022-09-15	micro	http://purl.obolibrary.org/obo/MICRO_0002999	HTTP 404	404
2022-09-15	millipore	https://www.merckmillipore.com/catalogue/item/SCC111	ReadTimeout	HTTPSConnectionPool(host='www.merckmillipore.com', port=443): Read timed out. (read timeout=15)
2022-09-15	mint	http://mint.bio.uniroma2.it/mint/search/inFrameInteraction.do?interactionAc=MINT-10000	HTTP 404	404
2022-09-15	mirtarbase	http://mirtarbase.mbc.nctu.edu.tw/php/detail.php?mirtid=MIRT000002	ConnectionError	HTTPConnectionPool(host='mirtarbase.mbc.nctu.edu.tw', port=80): Max retries exceeded with url: /php/detail.php?mirtid=MIRT000002 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11fa63520>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2022-09-15	mmmp.biomaps	http://www.mmmp.org/MMMP/public/biomap/viewBiomap.mmmp?id=37	HTTP 404	404
2022-09-15	mmp.cat	https://mmp.sfb.uit.no/databases/marcat/#/records/MMP743597.11	HTTP 404	404
2022-09-15	molbase	http://www.molbase.com/en/index.php?app=search&search_keyword=128796-39-4	HTTP 403	403
2022-09-15	molmedb	https://molmedb.upol.cz/mol/MM00040	SSLError	HTTPSConnectionPool(host='molmedb.upol.cz', port=443): Max retries exceeded with url: /mol/MM00040 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))
2022-09-15	mpid	http://www.jcvi.org/mpidb/experiment.php?interaction_id=172	HTTP 404	404
2022-09-15	multicellds	http://multicellds.org/MultiCellDB/MCDS_S_0000000001	HTTP 404	404
2022-09-15	multicellds.cell_line	http://multicellds.org/MultiCellDB/MCDS_L_0000000001	HTTP 404	404
2022-09-15	multicellds.collection	http://multicellds.org/MultiCellDB/MCDS_C_0000000001	HTTP 404	404
2022-09-15	multicellds.snapshot	http://multicellds.org/MultiCellDB/MCDS_S_0000000001	HTTP 404	404
2022-09-15	myco.lepra	http://mycobrowser.epfl.ch/leprosysearch.php?gene+name=ML0224	HTTP 404	404
2022-09-15	myco.marinum	http://mycobrowser.epfl.ch/marinosearch.php?gene+name=MMAR_2462	HTTP 404	404
2022-09-15	myco.smeg	http://mycobrowser.epfl.ch/smegmasearch.php?gene+name=MSMEG_3769	HTTP 404	404
2022-09-15	myco.tuber	http://tuberculist.epfl.ch/quicksearch.php?gene+name=Rv1908c	HTTP 404	404
2022-09-15	mycobank	http://www.mycobank.org/Biolomics.aspx?Table=Mycobank&MycoBankNr_=349124	HTTP 403	403
2022-09-15	napdi	https://repo.napdi.org/study/28	HTTP 404	404
2022-09-15	ncats.drug	https://drugs.ncats.io/drug/44259	HTTP 502	502
2022-09-15	ndfrt	https://evs.nci.nih.gov/ftp1/NDF-RT/NDF-RT.owl#N0000001662	HTTP 404	404
2022-09-15	neuromorpho	http://neuromorpho.org/neuron_info.jsp?neuron_name=Rosa2	SSLError	HTTPSConnectionPool(host='neuromorpho.org', port=443): Max retries exceeded with url: /neuron_info.jsp?neuron_name=Rosa2 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))
2022-09-15	niaest	http://lgsun.grc.nia.nih.gov/cgi-bin/pro3?sname1=J0705A10	ConnectionError	HTTPConnectionPool(host='lgsun.grc.nia.nih.gov', port=80): Max retries exceeded with url: /cgi-bin/pro3?sname1=J0705A10 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f892cd0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2022-09-15	nlx.cell	http://uri.neuinfo.org/nif/nifstd/nlx_cell_91005	HTTP 404	404
2022-09-15	nlx.chem	http://uri.neuinfo.org/nif/nifstd/nlx_chem_90801	HTTP 404	404
2022-09-15	nlx.dys	http://uri.neuinfo.org/nif/nifstd/nlx_dys_20090303	HTTP 404	404
2022-09-15	nlx.func	http://uri.neuinfo.org/nif/nifstd/nlx_func_90801	HTTP 404	404
2022-09-15	nlx.inv	http://uri.neuinfo.org/nif/nifstd/nlx_inv_90901	HTTP 404	404
2022-09-15	nlx.mol	http://uri.neuinfo.org/nif/nifstd/nlx_mol_90806	HTTP 404	404
2022-09-15	noncodev3	http://www.noncode.org/NONCODERv3/ncrna.php?ncid=377550	HTTP 404	404
2022-09-15	noncodev4.gene	http://www.bioinfo.org/NONCODEv4/show_gene.php?id=NONHSAG00001	ConnectionError	HTTPSConnectionPool(host='en.bioinfo.org', port=443): Max retries exceeded with url: /NONCODEv4/show_gene.php?id=NONHSAG00001 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11f8ac070>: Failed to establish a new connection: [Errno 61] Connection refused'))
2022-09-15	noncodev4.rna	http://www.bioinfo.org/NONCODEv4/show_rna.php?id=NONHSAT000001	ConnectionError	HTTPSConnectionPool(host='en.bioinfo.org', port=443): Max retries exceeded with url: /NONCODEv4/show_rna.php?id=NONHSAT000001 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11f8aca60>: Failed to establish a new connection: [Errno 61] Connection refused'))
2022-09-15	oci	https://w3id.org/oc/oci/1-18	HTTP 500	500
2022-09-15	oclc	https://www.worldcat.org/oclc/634515043	HTTP 503	503
2022-09-15	ogg	http://purl.obolibrary.org/obo/OGG_3000887619	HTTP 500	500
2022-09-15	om	http://www.ontology-of-units-of-measure.org/resource/om-2/Dimension	HTTP 404	404
2022-09-15	omim	https://omim.org/entry/603903	HTTP 403	403
2022-09-15	omim.ps	https://omim.org/phenotypicSeries/PS214100	HTTP 403	403
2022-09-15	omit	https://www.ebi.ac.uk/ols/ontologies/omit/terms?short_form=OMIT_0000069	HTTP 404	404
2022-09-15	opb	http://purl.bioontology.org/ontology/OPB?conceptid=http%3A%2F%2Fbhi.washington.edu%2FOPB%23OPB_00573	HTTP 404	404
2022-09-15	otl	http://oryzatagline.cirad.fr/cgi-bin/general_mutant.pl?line=AADB12	HTTP 403	403
2022-09-15	p3db.protein	http://www.p3db.org/protein.php?id=70&amp;ref=0	HTTP 404	404
2022-09-15	p3db.site	http://www.p3db.org/phosphosite.php?id=65&ref=0	HTTP 404	404
2022-09-15	paleodb	http://fossilworks.org/?a=taxonInfo&taxon_no=83088	ConnectionError	HTTPConnectionPool(host='fossilworks.org', port=80): Max retries exceeded with url: /?a=taxonInfo&taxon_no=83088 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f8a84f0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2022-09-15	pathwaycommons	http://www.pathwaycommons.org/pc/record2.do?id=485991	ReadTimeout	HTTPConnectionPool(host='www.pathwaycommons.org', port=80): Read timed out. (read timeout=15)
2022-09-15	pav	http://purl.org/pav/authoredBy	InvalidURL	No host specified.
2022-09-15	pazar	http://www.pazar.info/cgi-bin/tf_search.cgi?geneID=TF0001053	ConnectTimeout	HTTPConnectionPool(host='www.pazar.info', port=80): Max retries exceeded with url: /cgi-bin/tf_search.cgi?geneID=TF0001053 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x11f88abb0>, 'Connection to www.pazar.info timed out. (connect timeout=15)'))
2022-09-15	pdb.ligand	http://www.rcsb.org/pdb/ligand/ligandsummary.do?hetId=TRQ	HTTP 404	404
2022-09-15	pesticides	http://www.alanwood.net/pesticides/derivatives%2Fthiocyclam%20hydrochloride.html	HTTP 404	404
2022-09-15	phosphopoint.kinase	http://kinase.bioinformatics.tw/showall.jsp?type=Kinase&info=Gene&name=AURKA&drawing=0&sorting=0&kinome=1	ConnectionError	HTTPConnectionPool(host='kinase.bioinformatics.tw', port=80): Max retries exceeded with url: /showall.jsp?type=Kinase&info=Gene&name=AURKA&drawing=0&sorting=0&kinome=1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f82e520>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2022-09-15	phosphopoint.protein	http://kinase.bioinformatics.tw/showall.jsp?type=PhosphoProtein&info=Gene&name=AURKA&drawing=0&sorting=0&kinome=0	ConnectionError	HTTPConnectionPool(host='kinase.bioinformatics.tw', port=80): Max retries exceeded with url: /showall.jsp?type=PhosphoProtein&info=Gene&name=AURKA&drawing=0&sorting=0&kinome=0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f844880>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2022-09-15	phosphosite.protein	http://www.phosphosite.org/proteinAction.do?id=12300	HTTP 403	403
2022-09-15	phosphosite.residue	http://www.phosphosite.org/siteAction.do?id=2842	HTTP 403	403
2022-09-15	phytozome.locus	http://www.phytozome.net/genePage.php?crown&method=0&search=1&detail=1&searchText=locusname:Glyma0021s00410	HTTP 503	503
2022-09-15	pid.pathway	http://pid.nci.nih.gov/search/pathway_landing.shtml?what=graphic&jpg=on&pathway_id=eff796f3-6195-11e5-8ac5-06603eb7f303	ConnectionError	HTTPConnectionPool(host='pid.nci.nih.gov', port=80): Max retries exceeded with url: /search/pathway_landing.shtml?what=graphic&jpg=on&pathway_id=eff796f3-6195-11e5-8ac5-06603eb7f303 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11fa32d30>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2022-09-15	pina	http://cbg.garvan.unsw.edu.au/pina/interactome.oneP.do?showExtend=null&ac=Q13485	ConnectTimeout	HTTPConnectionPool(host='cbg.garvan.unsw.edu.au', port=80): Max retries exceeded with url: /pina/interactome.oneP.do?showExtend=null&ac=Q13485 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x11f837d00>, 'Connection to cbg.garvan.unsw.edu.au timed out. (connect timeout=15)'))
2022-09-15	pirsf	https://pir.georgetown.edu/cgi-bin/ipcSF?id=PIRSF000100	SSLError	"HTTPSConnectionPool(host='pir.georgetown.edu', port=443): Max retries exceeded with url: /cgi-bin/ipcSF?id=PIRSF000100 (Caused by SSLError(CertificateError(""hostname 'pir.georgetown.edu' doesn't match either of 'lod.proconsortium.org', 'tncentral.proteininformationresource.org', 'sparql.proconsortium.org', 'ftp.proteininformationresource.org', 'proconsortium.org', 'proteininformationresource.org', 'www.proteininformationresource.org'"")))"
2022-09-15	planttfdb	http://planttfdb.cbi.pku.edu.cn/tf.php?uid=Ath_AT1G01030.1	HTTP 404	404
2022-09-15	pmap.cutdb	http://cutdb.burnham.org/relation/show/25782	ConnectionError	HTTPConnectionPool(host='cutdb.burnham.org', port=80): Max retries exceeded with url: /relation/show/25782 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11fa7a670>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2022-09-15	pmap.substratedb	http://substrate.burnham.org/protein/annotation/1915/html	ConnectionError	HTTPConnectionPool(host='substrate.burnham.org', port=80): Max retries exceeded with url: /protein/annotation/1915/html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f7c50a0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2022-09-15	pmdb	https://bioinformatics.cineca.it/PMDB/user//search.php?idsearch=PM0012345	ConnectTimeout	HTTPSConnectionPool(host='bioinformatics.cineca.it', port=443): Max retries exceeded with url: /PMDB/user//search.php?idsearch=PM0012345 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x11f867610>, 'Connection to bioinformatics.cineca.it timed out. (connect timeout=15)'))
2022-09-15	pocketome	http://www.pocketome.org/files/1433C_TOBAC_1_252.html	ConnectTimeout	HTTPConnectionPool(host='www.pocketome.org', port=80): Max retries exceeded with url: /files/1433C_TOBAC_1_252.html (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x11fa84c10>, 'Connection to www.pocketome.org timed out. (connect timeout=15)'))
2022-09-15	proco	https://www.ebi.ac.uk/ols/ontologies/proco/terms?iri=http://purl.obolibrary.org/obo/PROCO_0000001	HTTP 404	404
2022-09-15	prodom	http://prodom.prabi.fr/prodom/current/cgi-bin/request.pl?question=DBEN&query=PD10000	ConnectTimeout	HTTPConnectionPool(host='prodom.prabi.fr', port=80): Max retries exceeded with url: /prodom/current/cgi-bin/request.pl?question=DBEN&query=PD10000 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x11f837df0>, 'Connection to prodom.prabi.fr timed out. (connect timeout=15)'))
2022-09-15	proglyc	http://www.proglycprot.org/detail.aspx?ProId=AC119	HTTP 404	404
2022-09-15	protonet.cluster	http://www.protonet.cs.huji.ac.il/requested/cluster_card.php?cluster=4349895	ConnectTimeout	HTTPConnectionPool(host='www.protonet.cs.huji.ac.il', port=80): Max retries exceeded with url: /requested/cluster_card.php?cluster=4349895 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x11fa63fa0>, 'Connection to www.protonet.cs.huji.ac.il timed out. (connect timeout=15)'))
2022-09-15	protonet.proteincard	http://www.protonet.cs.huji.ac.il/requested/protein_card.php?protein_id=16941567	ConnectTimeout	HTTPConnectionPool(host='www.protonet.cs.huji.ac.il', port=80): Max retries exceeded with url: /requested/protein_card.php?protein_id=16941567 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x11fa32250>, 'Connection to www.protonet.cs.huji.ac.il timed out. (connect timeout=15)'))
2022-09-15	px	http://proteomecentral.proteomexchange.org/cgi/GetDataset?ID=PXD000500	ReadTimeout	HTTPConnectionPool(host='proteomecentral.proteomexchange.org', port=80): Read timed out. (read timeout=15)
2022-09-15	rbk	https://www.rebuildingakidney.org/id/Q-2958	ReadTimeout	HTTPSConnectionPool(host='www.rebuildingakidney.org', port=443): Read timed out. (read timeout=15)
2022-09-15	rdo	http://www.semanticweb.org/mca/ontologies/2018/8/untitled-ontology-47#9002859	ConnectTimeout	HTTPConnectionPool(host='semanticweb.org', port=80): Max retries exceeded with url: /mca/ontologies/2018/8/untitled-ontology-47 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x11f8a48b0>, 'Connection to semanticweb.org timed out. (connect timeout=15)'))
2022-09-15	rebase	http://rebase.neb.com/rebase/enz/101.html	HTTP 403	403
2022-09-15	receptome.family	http://www.receptome.org/families/Frameset_family.asp?ProtType=Receptor&FamId=5.1	ConnectionError	HTTPConnectionPool(host='www.receptome.org', port=80): Max retries exceeded with url: /families/Frameset_family.asp?ProtType=Receptor&FamId=5.1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11fa36ee0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2022-09-15	rnamod	http://rna.rega.kuleuven.be/cgi-bin/rnamods/rnashow.pl?051	HTTP 404	404
2022-09-15	rnamods	http://mods.rna.albany.edu/mods/modifications/view/101	SSLError	HTTPSConnectionPool(host='mods.rna.albany.edu', port=443): Max retries exceeded with url: /mods/modifications/view/101 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1129)')))
2022-09-15	ro	http://purl.obolibrary.org/obo/RO_0002533	HTTP 404	404
2022-09-15	scholia.resource	https://bioregistry.io/metaregistry/scholia/doi	HTTP 404	404
2022-09-15	scop	http://scop.mrc-lmb.cam.ac.uk/scop/search.cgi?sunid=47419	HTTP 404	404
2022-09-15	scretf	http://stormo.wustl.edu/ScerTF/details/RSC3	ConnectionError	HTTPConnectionPool(host='stormo.wustl.edu', port=80): Max retries exceeded with url: /ScerTF/details/RSC3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f90d910>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2022-09-15	sedml.format	https://sed-ml.org/urns.html#format:csv	SSLError	HTTPSConnectionPool(host='sed-ml.org', port=443): Max retries exceeded with url: /urns.html (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))
2022-09-15	sedml.language	https://sed-ml.org/urns.html#language:sbml.level-3.version-2	SSLError	HTTPSConnectionPool(host='sed-ml.org', port=443): Max retries exceeded with url: /urns.html (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))
2022-09-15	sigmaaldrich	https://www.sigmaaldrich.com/US/en/product/sigma/HPA000698	ReadTimeout	HTTPSConnectionPool(host='www.sigmaaldrich.com', port=443): Read timed out. (read timeout=15)
2022-09-15	signaling-gateway	http://www.signaling-gateway.org/molecule/query?afcsid=A001094	ConnectionError	HTTPConnectionPool(host='www.signaling-gateway.org', port=80): Max retries exceeded with url: /molecule/query?afcsid=A001094 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f9455b0>: Failed to establish a new connection: [Errno 61] Connection refused'))
2022-09-15	sio	https://www.ebi.ac.uk/ols/ontologies/sio/terms?short_form=000912	HTTP 404	404
2022-09-15	sisu	http://search.sisuproject.fi/#/variant/17:41223048	SSLError	HTTPSConnectionPool(host='search.sisuproject.fi', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))
2022-09-15	sitex	http://www-bionet.sscc.ru/sitex/index.php?siteid=1000	HTTP 403	403
2022-09-15	slkbase	https://sumlineknowledgebase.com/?page_id=3618	HTTP 406	406
2022-09-15	soybase	http://www.soybase.org/sbt/search/search_results.php?category=SNP&search_term=BARC-013845-01256	ConnectionError	HTTPConnectionPool(host='www.soybase.org', port=80): Max retries exceeded with url: /sbt/search/search_results.php?category=SNP&search_term=BARC-013845-01256 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f955910>: Failed to establish a new connection: [Errno 61] Connection refused'))
2022-09-15	stap	http://psb.kobic.re.kr/STAP/refinement1/result.php?search=1a24	ConnectTimeout	HTTPConnectionPool(host='psb.kobic.re.kr', port=80): Max retries exceeded with url: /STAP/refinement1/result.php?search=1a24 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x11f908d30>, 'Connection to psb.kobic.re.kr timed out. (connect timeout=15)'))
2022-09-15	string	http://string.embl.de/interactions/P53350	HTTP 404	404
2022-09-15	swo	http://purl.obolibrary.org/obo/SWO_0000144	HTTP 404	404
2022-09-15	tkg	http://www2.idac.tohoku.ac.jp/dep/ccr/TKGdate/TKGvol08/0221.html	HTTP 404	404
2022-09-15	ttd.drug	http://bidd.nus.edu.sg/group/TTD/ZFTTDDRUG.asp?ID=DAP000773	ConnectTimeout	HTTPConnectionPool(host='bidd.nus.edu.sg', port=80): Max retries exceeded with url: /group/TTD/ZFTTDDRUG.asp?ID=DAP000773 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x11f9199d0>, 'Connection to bidd.nus.edu.sg timed out. (connect timeout=15)'))
2022-09-15	ttd.target	http://bidd.nus.edu.sg/group/TTD/ZFTTDDetail.asp?ID=TTDS00056	ConnectTimeout	HTTPConnectionPool(host='bidd.nus.edu.sg', port=80): Max retries exceeded with url: /group/TTD/ZFTTDDetail.asp?ID=TTDS00056 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x11efccbb0>, 'Connection to bidd.nus.edu.sg timed out. (connect timeout=15)'))
2022-09-15	ubio.namebank	http://www.ubio.org/browser/details.php?namebankID=2555646	ConnectTimeout	HTTPConnectionPool(host='www.ubio.org', port=80): Max retries exceeded with url: /browser/details.php?namebankID=2555646 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x11f874910>, 'Connection to www.ubio.org timed out. (connect timeout=15)'))
2022-09-15	ucsc	ftp://hgdownload.cse.ucsc.edu/goldenPath/uc001rvw.5	InvalidSchema	No connection adapters were found for 'ftp://hgdownload.cse.ucsc.edu/goldenPath/uc001rvw.5'
2022-09-15	umbbd.compound	http://eawag-bbd.ethz.ch/servlets/pageservlet?ptype=c&compID=c0001	ReadTimeout	HTTPConnectionPool(host='eawag-bbd.ethz.ch', port=80): Read timed out. (read timeout=15)
2022-09-15	umbbd.enzyme	http://eawag-bbd.ethz.ch/servlets/pageservlet?ptype=ep&enzymeID=e0333	ReadTimeout	HTTPConnectionPool(host='eawag-bbd.ethz.ch', port=80): Read timed out. (read timeout=15)
2022-09-15	umbbd.reaction	http://eawag-bbd.ethz.ch/servlets/pageservlet?ptype=r&reacID=r0001	ReadTimeout	HTTPConnectionPool(host='eawag-bbd.ethz.ch', port=80): Read timed out. (read timeout=15)
2022-09-15	umbbd.rule	http://www.umbbd.ethz.ch/servlets/rule.jsp?rule=bt0001	ReadTimeout	HTTPConnectionPool(host='eawag-bbd.ethz.ch', port=80): Read timed out. (read timeout=15)
2022-09-15	unigene	http://www.ncbi.nlm.nih.gov/UniGene/clust.cgi?UGID=4900	HTTP 410	410
2022-09-15	uniparc	https://www.ebi.ac.uk/cgi-bin/dbfetch?db=uniparc&id=UPI000000000A	HTTP 500	500
2022-09-15	unists	https://www.ncbi.nlm.nih.gov/genome/sts/sts.cgi?uid=456789	HTTP 410	410
2022-09-15	uspto	http://patft.uspto.gov/netacgi/nph-Parser?Sect2=PTO1&Sect2=HITOFF&p=1&u=/netahtml/PTO/search-bool.html&r=1&f=G&l=50&d=PALL&RefSrch=yes&Query=PN/4145692	ConnectionError	('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))
2022-09-15	vann	https://vocab.org/vann/usageNote	HTTP 404	404
2022-09-15	vbrc	http://vbrc.org/gene_detail.asp?gene_id=35742	HTTP 404	404
2022-09-15	vipr	http://www.viprbrc.org/brc/viprStrainDetails.do?strainName=BeAn 70563&decorator=arena	HTTP 404	404
2022-09-15	worfdb	http://worfdb.dfci.harvard.edu/index.php?search_type=name&page=showresultrc&race_query=T01B6.1	HTTP 404	404
2022-09-15	ydpm	http://www-deletion.stanford.edu/cgi-bin/YDPM/YDPM_search.cgi?thelist=YAL001C	ConnectTimeout	HTTPConnectionPool(host='www-deletion.stanford.edu', port=80): Max retries exceeded with url: /cgi-bin/YDPM/YDPM_search.cgi?thelist=YAL001C (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x11f98a850>, 'Connection to www-deletion.stanford.edu timed out. (connect timeout=15)'))
2022-09-15	yid	http://metarray.ucsc.edu/cgi-bin/intron/yirIntrondb?orfName=SNR17A	ConnectTimeout	HTTPConnectionPool(host='metarray.ucsc.edu', port=80): Max retries exceeded with url: /cgi-bin/intron/yirIntrondb?orfName=SNR17A (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x11f9556a0>, 'Connection to metarray.ucsc.edu timed out. (connect timeout=15)'))
